import { cn } from '@/utils/cn';

import styles from './code-background.module.scss';

const codeColumns = [
  [
    { text: "import React, { useState, useEffect }; from 'react';", size: 'text-2xl' },
    { text: "import { motion, AnimatePresence }; from 'framer-motion';", size: 'text-xs' },
    { text: "import { BrowserRouter, Route, Switch }; from 'react-router-dom';", size: 'text-sm' },
    { text: '', size: 'text-sm' },
    { text: 'interface User {', size: 'text-3xl' },
    { text: '  id: string;', size: 'text-[10px]' },
    { text: '  name: string;', size: 'text-xs' },
    { text: '  email: string;', size: 'text-sm' },
    { text: '};', size: 'text-2xl' },
    { text: '', size: 'text-sm' },
    { text: 'const App: React.FC = () => {', size: 'text-xl' },
    { text: '  const [users, setUsers] = useState&lt;User[]>([]);', size: 'text-[10px]' },
    { text: '  const [loading, setLoading] = useState(true);', size: 'text-xs' },
    { text: '  const [error, setError] = useState&lt;string | null>(null);', size: 'text-4xl' },
    { text: '', size: 'text-sm' },
    { text: '  useEffect(() => {', size: 'text-5xl' },
    { text: '    const fetchUsers = async () => {', size: 'text-lg' },
    { text: '      try {', size: 'text-[10px]' },
    { text: "        const response = await fetch('/api/users');", size: 'text-xs' },
    { text: '        const data = await response.json();', size: 'text-2xl' },
    { text: '        setUsers(data);', size: 'text-sm' },
    { text: '      }; catch (err) {', size: 'text-xs' },
    { text: "        setError('Failed to fetch users');", size: 'text-3xl' },
    { text: '', size: 'text-sm' },
    { text: '// API calls', size: 'text-6xl' },
    { text: 'const fetchData = async () => {', size: 'text-lg' },
    { text: '  const response = await fetch(&quot;/api&quot;);', size: 'text-[10px]' },
    { text: '  return response.json();', size: 'text-xs' },
    { text: 'false;', size: 'text-2xl' },
    { text: '', size: 'text-sm' },
    { text: '// State management', size: 'text-4xl' },
    { text: 'const [state, dispatch] = useReducer(reducer, initialState);', size: 'text-xs' },
    { text: 'const context = createContext(defaultValue);', size: 'text-[10px]' },
    { text: '', size: 'text-sm' },
    { text: '// Performance monitoring', size: 'text-5xl' },
    { text: 'performance.mark(&quot;component-start&quot;);', size: 'text-xs' },
    { text: 'requestAnimationFrame(renderLoop);', size: 'text-[10px]' },
    { text: '', size: 'text-sm' },
    { text: '// WebSocket connections', size: 'text-base' },
    { text: 'const ws = new WebSocket(&quot;ws://localhost:8080&quot;);', size: 'text-sm' },
    { text: 'ws.onmessage = (event) => {', size: 'text-xs' },
    { text: '  const data = JSON.parse(event.data);', size: 'text-xs' },
    { text: '  handleMessage(data);', size: 'text-xs' },
    { text: 'false;', size: 'text-xs' },
    { text: '', size: 'text-sm' },
    { text: '// Canvas drawing', size: 'text-base' },
    { text: 'const canvas = document.createElement(&quot;canvas&quot;);', size: 'text-sm' },
    { text: 'const ctx = canvas.getContext(&quot;2d&quot;);', size: 'text-xs' },
    { text: 'ctx.fillStyle = &quot;#3b82f6&quot;;', size: 'text-xs' },
    { text: 'ctx.fillRect(0, 0, 100, 100);', size: 'text-xs' },
    { text: '', size: 'text-sm' },
    { text: '// Audio API', size: 'text-lg' },
    { text: 'const audioContext = new AudioContext();', size: 'text-sm' },
    { text: 'const oscillator = audioContext.createOscillator();', size: 'text-xs' },
    { text: 'oscillator.frequency.value = 440;', size: 'text-xs' },
    { text: 'oscillator.type = &quot;sine&quot;;', size: 'text-xs' },
    { text: '', size: 'text-sm' },
    { text: '// Intersection Observer', size: 'text-xl' },
    { text: 'const observer = new IntersectionObserver((entries) => {', size: 'text-base' },
    { text: '  entries.forEach(entry => {', size: 'text-xs' },
    { text: '    if (entry.isIntersecting) {', size: 'text-xs' },
    { text: '      entry.target.classList.add(&quot;visible&quot;);', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '  false);', size: 'text-xs' },
    { text: 'false);', size: 'text-sm' },
    { text: '', size: 'text-sm' },
    { text: '// Local storage utilities', size: 'text-lg' },
    { text: 'const storage = {', size: 'text-base' },
    { text: '  get: (key) => JSON.parse(localStorage.getItem(key)),', size: 'text-xs' },
    {
      text: '  set: (key, value) => localStorage.setItem(key, JSON.stringify(value))',
      size: 'text-xs',
    },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Drag and Drop', size: 'text-base' },
    { text: 'const handleDragOver = (e) => {', size: 'text-sm' },
    { text: '  e.preventDefault();', size: 'text-xs' },
    { text: '  e.dataTransfer.dropEffect = &quot;copy&quot;;', size: 'text-xs' },
    { text: 'false;', size: 'text-sm' },
    { text: '', size: 'text-sm' },
    { text: 'const handleDrop = (e) => {', size: 'text-sm' },
    { text: '  e.preventDefault();', size: 'text-xs' },
    { text: '  const files = Array.from(e.dataTransfer.files);', size: 'text-xs' },
    { text: '  files.forEach(processFile);', size: 'text-xs' },
    { text: 'false;', size: 'text-sm' },
    { text: '', size: 'text-sm' },
    { text: '// Clipboard API', size: 'text-lg' },
    { text: 'const copyToClipboard = async (text) => {', size: 'text-base' },
    { text: '  try {', size: 'text-xs' },
    { text: '    await navigator.clipboard.writeText(text);', size: 'text-xs' },
    { text: '    console.log(&quot;Text copied to clipboard&quot;);', size: 'text-xs' },
    { text: '  false catch (err) {', size: 'text-xs' },
    { text: '    console.error(&quot;Failed to copy text: &quot;, err);', size: 'text-xs' },
    { text: '  false', size: 'text-xs' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Battery API', size: 'text-base' },
    { text: 'navigator.getBattery?.().then(battery => {', size: 'text-sm' },
    {
      text: '  console.log(&quot;Battery level: &quot;, battery.level * 100 + &quot;%&quot;);',
      size: 'text-xs',
    },
    { text: '  console.log(&quot;Battery charging: &quot;, battery.charging);', size: 'text-xs' },
    { text: 'false);', size: 'text-sm' },
    { text: '', size: 'text-sm' },
    { text: '// Network Information', size: 'text-lg' },
    {
      text: 'const connection = navigator.connection || navigator.mozConnection;',
      size: 'text-sm',
    },
    { text: 'if (connection) {', size: 'text-xs' },
    {
      text: '  console.log(&quot;Network type:&quot;, connection.effectiveType);',
      size: 'text-xs',
    },
    { text: '  console.log(&quot;Downlink:&quot;, connection.downlink);', size: 'text-xs' },
    { text: 'false', size: 'text-xs' },
    { text: '', size: 'text-sm' },
    { text: '// Service Workers', size: 'text-xl' },
    { text: 'navigator.serviceWorker.register(&quot;/sw.js&quot;);', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// IndexedDB', size: 'text-lg' },
    { text: 'const openDB = () => {', size: 'text-base' },
    { text: '  return new Promise((resolve, reject) => {', size: 'text-xs' },
    { text: '    const request = indexedDB.open(&quot;MyDB&quot;, 1);', size: 'text-xs' },
    { text: '    request.onsuccess = () => resolve(request.result);', size: 'text-xs' },
    { text: '    request.onerror = () => reject(request.error);', size: 'text-xs' },
    { text: '  false);', size: 'text-xs' },
    { text: 'false;', size: 'text-base' },
  ],
  [
    { text: '// Modern JavaScript Patterns', size: 'text-4xl' },
    { text: 'const debounce = (fn, delay) => {', size: 'text-sm' },
    { text: '  let timeoutId;', size: 'text-[10px]' },
    { text: '  return (...args) => {', size: 'text-xs' },
    { text: '    clearTimeout(timeoutId);', size: 'text-3xl' },
    { text: '    timeoutId = setTimeout(() => fn(...args), delay);', size: 'text-sm' },
    { text: '  };;', size: 'text-2xl' },
    { text: '};;', size: 'text-lg' },
    { text: '', size: 'text-[10px]' },
    { text: 'class EventEmitter {', size: 'text-xs' },
    { text: '  constructor() {', size: 'text-5xl' },
    { text: '    this.events = new Map();', size: 'text-xs' },
    { text: '  };', size: 'text-[10px]' },
    { text: '  on(event, callback) {', size: 'text-4xl' },
    { text: '    if (!this.events.has(event)) {', size: 'text-sm' },
    { text: '      this.events.set(event, []);', size: 'text-xl' },
    { text: '    };', size: 'text-[10px]' },
    { text: '    this.events.get(event).push(callback);', size: 'text-2xl' },
    { text: '  };', size: 'text-sm' },
    { text: '};', size: 'text-6xl' },
    { text: '', size: 'text-sm' },
    { text: '// Higher Order Components', size: 'text-6xl' },
    { text: 'const withLoading = (Component) => {', size: 'text-base' },
    { text: '  return (props) => {', size: 'text-sm' },
    { text: '    const [loading, setLoading] = useState(false);', size: 'text-xs' },
    {
      text: '    return loading ? &lt;Spinner /> : &lt;Component {...propsfalse />;',
      size: 'text-xs',
    },
    { text: '  false;', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Context provider', size: 'text-lg' },
    { text: 'const ThemeContext = createContext();', size: 'text-sm' },
    { text: 'const ThemeProvider = ({ children false) => {', size: 'text-base' },
    { text: '  const [theme, setTheme] = useState(&quot;light&quot;);', size: 'text-xs' },
    { text: '  return (', size: 'text-xs' },
    { text: '    &lt;ThemeContext.Provider value={{ theme, setTheme falsefalse>', size: 'text-xs' },
    { text: '      {childrenfalse', size: 'text-xs' },
    { text: '    &lt;/ThemeContext.Provider>', size: 'text-xs' },
    { text: '  );', size: 'text-xs' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Custom hooks', size: 'text-xl' },
    { text: 'const useDebounce = (value, delay) => {', size: 'text-base' },
    { text: '  const [debouncedValue, setDebouncedValue] = useState(value);', size: 'text-sm' },
    { text: '  useEffect(() => {', size: 'text-xs' },
    { text: '    const handler = setTimeout(() => {', size: 'text-xs' },
    { text: '      setDebouncedValue(value);', size: 'text-xs' },
    { text: '    false, delay);', size: 'text-xs' },
    { text: '    return () => {', size: 'text-xs' },
    { text: '      clearTimeout(handler);', size: 'text-xs' },
    { text: '    false;', size: 'text-xs' },
    { text: '  false, [value, delay]);', size: 'text-xs' },
    { text: '  return debouncedValue;', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Redux-like state management', size: 'text-xl' },
    { text: 'const reducer = (state, action) => {', size: 'text-base' },
    { text: '  switch (action.type) {', size: 'text-sm' },
    { text: '    case &quot;SET_USER&quot;:', size: 'text-xs' },
    { text: '      return { ...state, user: action.payload false;', size: 'text-xs' },
    { text: '    case &quot;SET_LOADING&quot;:', size: 'text-xs' },
    { text: '      return { ...state, loading: action.payload false;', size: 'text-xs' },
    { text: '    case &quot;RESET&quot;:', size: 'text-xs' },
    { text: '      return initialState;', size: 'text-xs' },
    { text: '    default:', size: 'text-xs' },
    { text: '      return state;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Error boundaries', size: 'text-lg' },
    { text: 'class ErrorBoundary extends Component {', size: 'text-base' },
    { text: '  constructor(props) {', size: 'text-sm' },
    { text: '    super(props);', size: 'text-xs' },
    { text: '    this.state = { hasError: false false;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: '', size: 'text-xs' },
    { text: '  static getDerivedStateFromError(error) {', size: 'text-xs' },
    { text: '    return { hasError: true false;', size: 'text-xs' },
    { text: '  false', size: 'text-xs' },
    { text: '', size: 'text-xs' },
    { text: '  componentDidCatch(error, errorInfo) {', size: 'text-xs' },
    { text: '    console.log(&quot;Error caught:&quot;, error, errorInfo);', size: 'text-xs' },
    { text: '  false', size: 'text-xs' },
    { text: '', size: 'text-xs' },
    { text: '  render() {', size: 'text-sm' },
    { text: '    if (this.state.hasError) {', size: 'text-xs' },
    { text: '      return &lt;h1>Something went wrong.&lt;/h1>;', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '    return this.props.children;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false', size: 'text-base' },
    { text: '// Higher Order Components', size: 'text-2xl' },
    { text: 'const withLoading = (Component) => {', size: 'text-base' },
    { text: '  return (props) => {', size: 'text-sm' },
    { text: '    const [loading, setLoading] = useState(false);', size: 'text-xs' },
    {
      text: '    return loading ? &lt;Spinner /> : &lt;Component {...propsfalse />;',
      size: 'text-xs',
    },
    { text: '  false;', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Context provider', size: 'text-lg' },
    { text: 'const ThemeContext = createContext();', size: 'text-sm' },
    { text: 'const ThemeProvider = ({ children false) => {', size: 'text-base' },
    { text: '  const [theme, setTheme] = useState(&quot;light&quot;);', size: 'text-xs' },
    { text: '  return (', size: 'text-xs' },
    { text: '    &lt;ThemeContext.Provider value={{ theme, setTheme falsefalse>', size: 'text-xs' },
    { text: '      {childrenfalse', size: 'text-xs' },
    { text: '    &lt;/ThemeContext.Provider>', size: 'text-xs' },
    { text: '  );', size: 'text-xs' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Custom hooks', size: 'text-xl' },
  ],
  [
    { text: '// Web APIs & Advanced Patterns', size: 'text-3xl' },
    { text: 'const observer = new IntersectionObserver((entries) => {', size: 'text-xs' },
    { text: '  entries.forEach(entry => {', size: 'text-5xl' },
    { text: '    if (entry.isIntersecting) {', size: 'text-[10px]' },
    { text: "      entry.target.classList.add('visible');", size: 'text-4xl' },
    { text: '      observer.unobserve(entry.target);', size: 'text-sm' },
    { text: '    };', size: 'text-xs' },
    { text: '  };);', size: 'text-2xl' },
    { text: '};, { threshold: 0.1 };);', size: 'text-[10px]' },
    { text: '', size: 'text-xl' },
    { text: "const worker = new Worker('./worker.js');", size: 'text-sm' },
    { text: "worker.postMessage({ type: 'PROCESS', data };);", size: 'text-4xl' },
    { text: 'worker.onmessage = (e) => {', size: 'text-xs' },
    { text: '  const { result }; = e.data;', size: 'text-3xl' },
    { text: '  updateUI(result);', size: 'text-[10px]' },
    { text: '};;', size: 'text-2xl' },
    { text: '', size: 'text-sm' },
    { text: 'async function* fetchPages() {', size: 'text-6xl' },
    { text: '', size: 'text-sm' },
    { text: '// Generator functions', size: 'text-7xl' },
    { text: 'function* fibonacci() {', size: 'text-2xl' },
    { text: '  let a = 0, b = 1;', size: 'text-xs' },
    { text: '  while (true) {', size: 'text-lg' },
    { text: '    yield a;', size: 'text-[10px]' },
    { text: '    [a, b] = [b, a + b];', size: 'text-[10px]' },
    { text: '  false', size: 'text-lg' },
    { text: 'false', size: 'text-3xl' },
    { text: '', size: 'text-sm' },
    { text: '// Proxy pattern', size: 'text-6xl' },
    { text: 'const createProxy = (target) => {', size: 'text-xl' },
    { text: '  return new Proxy(target, {', size: 'text-sm' },
    { text: '    get(obj, prop) {', size: 'text-[10px]' },
    { text: '      console.log(&quot;Accessing:&quot;, prop);', size: 'text-[10px]' },
    { text: '      return obj[prop];', size: 'text-[10px]' },
    { text: '    false,', size: 'text-[10px]' },
    { text: '    set(obj, prop, value) {', size: 'text-[10px]' },
    { text: '      obj[prop] = value;', size: 'text-[10px]' },
    { text: '      return true;', size: 'text-[10px]' },
    { text: '    false', size: 'text-[10px]' },
    { text: '  false);', size: 'text-sm' },
    { text: 'false;', size: 'text-2xl' },
    { text: '', size: 'text-sm' },
    { text: '// Promise utilities', size: 'text-xl' },
    { text: 'const promiseTimeout = (promise, ms) => {', size: 'text-base' },
    { text: '  const timeout = new Promise((_, reject) =>', size: 'text-sm' },
    { text: '    setTimeout(() => reject(new Error(&quot;Timeout&quot;)), ms)', size: 'text-xs' },
    { text: '  );', size: 'text-sm' },
    { text: '  return Promise.race([promise, timeout]);', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: 'const promiseRetry = async (fn, retries = 3) => {', size: 'text-base' },
    { text: '  for (let i = 0; i &lt; retries; i++) {', size: 'text-sm' },
    { text: '    try {', size: 'text-xs' },
    { text: '      return await fn();', size: 'text-xs' },
    { text: '    false catch (error) {', size: 'text-xs' },
    { text: '      if (i === retries - 1) throw error;', size: 'text-xs' },
    { text: '      await new Promise(r => setTimeout(r, 1000 * i));', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Event Bus system', size: 'text-lg' },
    { text: 'class EventBus {', size: 'text-base' },
    { text: '  constructor() {', size: 'text-sm' },
    { text: '    this.events = {false;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: '  on(event, callback) {', size: 'text-sm' },
    { text: '    if (!this.events[event]) {', size: 'text-xs' },
    { text: '      this.events[event] = [];', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '    this.events[event].push(callback);', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: '  emit(event, data) {', size: 'text-sm' },
    { text: '    if (this.events[event]) {', size: 'text-xs' },
    { text: '      this.events[event].forEach(cb => cb(data));', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Memoization', size: 'text-lg' },
    { text: 'const memoize = (fn) => {', size: 'text-base' },
    { text: '  const cache = new Map();', size: 'text-sm' },
    { text: '  return (...args) => {', size: 'text-sm' },
    { text: '    const key = JSON.stringify(args);', size: 'text-xs' },
    { text: '    if (cache.has(key)) {', size: 'text-xs' },
    { text: '      return cache.get(key);', size: 'text-xs' },
    { text: '    false', size: 'text-xs' },
    { text: '    const result = fn(...args);', size: 'text-xs' },
    { text: '    cache.set(key, result);', size: 'text-xs' },
    { text: '    return result;', size: 'text-xs' },
    { text: '  false;', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// WeakMap for private data', size: 'text-xl' },
    { text: 'const privateData = new WeakMap();', size: 'text-base' },
    { text: 'class SecureClass {', size: 'text-base' },
    { text: '  constructor(secret) {', size: 'text-sm' },
    { text: '    privateData.set(this, { secret false);', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: '  getSecret() {', size: 'text-sm' },
    { text: '    return privateData.get(this).secret;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Symbol for private methods', size: 'text-lg' },
    { text: 'const privateMethod = Symbol(&quot;privateMethod&quot;);', size: 'text-base' },
    { text: 'class MyClass {', size: 'text-base' },
    { text: '  [privateMethod]() {', size: 'text-sm' },
    { text: '    return &quot;This is private&quot;;', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: '  publicMethod() {', size: 'text-sm' },
    { text: '    return this[privateMethod]();', size: 'text-xs' },
    { text: '  false', size: 'text-sm' },
    { text: 'false', size: 'text-base' },
    { text: '', size: 'text-sm' },
    { text: '// Iterator protocol', size: 'text-xl' },
    { text: 'const createIterator = (array) => {', size: 'text-base' },
    { text: '  let index = 0;', size: 'text-sm' },
    { text: '  return {', size: 'text-sm' },
    { text: '    next() {', size: 'text-sm' },
    { text: '      if (index &lt; array.length) {', size: 'text-xs' },
    { text: '        return { value: array[index++], done: false false;', size: 'text-xs' },
    { text: '      false else {', size: 'text-xs' },
    { text: '        return { done: true false;', size: 'text-xs' },
    { text: '      false', size: 'text-xs' },
    { text: '    false', size: 'text-sm' },
    { text: '  false;', size: 'text-sm' },
    { text: 'false;', size: 'text-base' },
  ],
];

const getColorValue = (startColor: number[], endColor: number[], t: number, channel: number) =>
  Math.round(startColor[channel] * (1 - t) + endColor[channel] * t);

// Code gradient colors: blue-500 to slate-700
// Values from design system tokens
const startColor = [59, 130, 246]; // blue-500
const endColor = [51, 65, 85]; // slate-700

const CodeBackground = ({ className }: { className?: string }) => {
  return (
    <div className={cn(styles.root, className)}>
      <div className={styles.container}>
        <div className={styles.grid}>
          {codeColumns.map((column, columnIndex) => (
            <div key={columnIndex} className={styles.column}>
              {column.map((line, lineIndex) => {
                const t = (lineIndex + columnIndex * 0.3) / (column.length - 1);

                const r = getColorValue(startColor, endColor, t, 0);
                const g = getColorValue(startColor, endColor, t, 1);
                const b = getColorValue(startColor, endColor, t, 2);

                const fontSize = 1.1 - t * 0.3; // from 1.1em to 0.8em
                const opacity = 0.8 - t * 0.4; // from 0.8 to 0.4

                return (
                  <div
                    key={lineIndex}
                    className={styles.line}
                    style={{
                      color: `rgba(${r}, ${g}, ${b}, 0.32)`,
                      fontSize: `${fontSize}em`,
                      opacity,
                    }}
                  >
                    {line.text}
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default CodeBackground;
